### ISSUE TITLE
[Story] 新規ユーザーが、サービスに登録する前にEagnaのことを知れる

### ISSUE THREAD

**Issue by AtsukiTak** [eagna-io/Eagna#1]
新規ユーザーが、サービスに登録する前にEagnaのことを知れる
===

### 誰にとって価値のあるストーリーですか？

- 新規ユーザー

### 現状、どのような問題がありますか？

- 新規ユーザーがEagnaに興味を抱くためのコンテンツがサービス上にない
  - Eagna上にどのようなMarketがあるのか
  - Eagnaで何ができるか
  - Eagnaに登録すると何が嬉しいか

### その問題をどのように解決しますか？

- 新規ユーザーに、Eagna運営がおすすめする、featured marketの一覧をトップページで見せる
  - 実際はログインしていないユーザーに対してやる
  - 一番featureしたいのはOpen状態のもの
  - 次にPreparing状態のもの
  - Closed, Settledのマーケットもいくつか（面白そうだとユーザーが思うもの）
- 新規ユーザーに、Eagnaに登録すると何ができるか、何が嬉しいか、の説明をトップページで見せる

### その問題を解決する手段として、どのような代替手段が思いつきますか？また、なぜその手段を選択しないのですか？

- featured market一覧ではなく、全marketの一覧を見れるようにする
  - marketの数が多くなった時にしんどい
  - 定期的に繰り返しているMarketなど、いくつも見せてもしょうがないものもあるので、その辺を運営でコントロールしたい
- サービスの外部(noteとか)で見せる
  - せっかくサービスページに来たユーザー(新規)を、外部サイトに飛ばしてしまうのはもったいない
  - featured market一覧で興味を持ってもらい、そのままsign upの方がいい

### どのような作業が想定されますか？

e.g.
- [x] 修正したトップページのモックを作成する
- [x] モックを実装する
- [x] featured market一覧を返すAPIとして、Upcoming, Open状態のMarket一覧を返すAPIを実装する

**Comment by AtsukiTak** [comment]
まずトップページのモック作ろう @Yuya-Furusawa 

## 載せる情報
- sign up form
- Eagnaとは（一言で）
- Eagnaを使うと何が嬉しいか
- Eagnaの使い方

**Comment by AtsukiTak** [comment]
Eagnaの使い方要らないか？

**Comment by Yuya-Furusawa** [comment]
トップページにはいらないかもしれない
noteとかで別に書いてそこへのlink貼っとくとか（前はそんな感じだった）

**Comment by AtsukiTak** [comment]
なんか、詳しい説明じゃなくて、3ステップくらいの簡単な説明をトップページには置きたい感ある

**Comment by Yuya-Furusawa** [comment]
[Augur in 3 steps](https://www.augur.net/test/?utm_expid=195388066-6.8_t1YxvKT-KngzToWCyJug.1&utm_referrer=https%3A%2F%2Fwww.google.com%2F)みたいな？
確かにこれあるのはいいけど一朝一夕では難しいなぁ
あとは動画とかをのっけるパターン結構多かった（CashとかBaseとか）

**Comment by AtsukiTak** [comment]
> Augur in 3 stepsみたいな？

まさに。

> 確かにこれあるのはいいけど一朝一夕では難しいなぁ

今回はスコープから外す？
そんなに難しい操作でもないし

**Comment by AtsukiTak** [comment]
フロントの実装Done
