### ISSUE TITLE
[Story] ユーザーが、運営からのメッセージを確認できるようにする

### ISSUE THREAD

**Issue by Yuya-Furusawa** [eagna-io/Eagna#30]
ユーザーが、運営からのメッセージを確認できるようにする。
===

### 誰にとって価値のあるストーリーですか？

- ユーザー 
- Eagna 

### 現状、どのような問題がありますか？

- Eagna運営が新たな情報（新機能の追加など）をユーザーに届ける手段に乏しい
- ユーザーが報酬を受け取ったことをメールでしか確認できない
    - 迷惑メールボックスとかに入ってしまったら認知されない

### その問題をどのように解決しますか？

- アカウント画面に「お知らせ」フォームを作成しそこに運営からの情報を載せる
    - 新機能のリリース
    - 報酬の当選

### その解決策によりどのような不利益が発生しますか？

- お知らせ作成フローを作成、確立させる必要
- お知らせ管理タスク

### その問題を解決する手段として、どのような代替手段が思いつきますか？また、なぜその手段を選択しないのですか？

- トップページに運営からのお知らせ情報を載せる
    - 個人的なお知らせができない
- noteとかに情報載せる
    - 個人的なお知らせができない
    - noteにいちいち飛ばすことでユーザーの負担増加（お知らせ見てくれないかもしれない）

### どのような作業が想定されますか？

- [ ] お知らせ作成のフローを作成する
- [ ] 修正したアカウントページのモックを作成する
- [ ] モックを実装する
- [ ] お知らせを作成するAPIを実装する
- [ ] お知らせを管理するAPIを実装する

**Comment by Yuya-Furusawa** [comment]
ユーザーに告知したいこと
- 新機能の追加
- 報酬の配布
- noteの更新
- 勉強会の開催
- Eagnaの活動(資本提携、業務提携みたいな)

**Comment by AtsukiTak** [comment]
## 代替手段
- メール
  - 見ない人もいる
  - Eagnaとどっちが見るかってなると、メールでは？

**Comment by Yuya-Furusawa** [comment]
2019/08/29 MTG
- 全体通知だけをとりあえず作成
    - 新機能追加しました
    - 報酬配布しました

**Comment by AtsukiTak** [comment]
表記の課題はとりあえず解決したのでcloseします
