### ISSUE TITLE
[Story] ユーザーが、マーケット画面で予測市場のルールを確認できるようにする

### ISSUE THREAD

**Issue by Yuya-Furusawa** [eagna-io/Eagna#32]
ユーザーが、マーケット画面で予測市場のルールを確認できるようにする
===

### 誰にとって価値のあるストーリーですか？

- ユーザー 

### 現状、どのような問題がありますか？

- note等を読まないと予測市場のルール（売ることもできる、当たったらその分コインがもらえる）を知ることができない
- ルールを知らないがために思ったように行動してくれない
- ルールを知らないがために使ってくれない（知らないものは使わない）

### その問題をどのように解決しますか？

- マーケットページに以下のことを記載する
    - 売買ができること
    - 当たったらその分コインがもらえること
    - 自分の予想通りに買うこと(???)

### その解決策によりどのような不利益が発生しますか？

- UIがごちゃつく
- ルールをすでに知っている人に対してはどうすればいいか？

### その問題を解決する手段として、どのような代替手段が思いつきますか？また、なぜその手段を選択しないのですか？

- noteへのリンクを貼る
    - noteにいちいち飛ばすのはユーザーの負担増
- トップページに記載
    - マーケットページの方が目に留まるor印象つけられる

### どのような作業が想定されますか？

- [ ] 記載する文言を考える
- [ ] 修正したマーケットページのモックを作成する
- [ ] モックを実装する

**Comment by Yuya-Furusawa** [comment]
掲載文言
- オープン期間中は自由にトークンを**売買**することができます
- 実現した結果のトークンは**1000Coin**に、実現しなかった結果のトークンは**0Coin**に置きかわります

**Comment by Yuya-Furusawa** [comment]
- 「支払う・受け取るコインの量=トークン価格×売買トークン量」にならない

ということも必要か？？

**Comment by AtsukiTak** [comment]
これってEagna in 3 stepsで解決した？

**Comment by Yuya-Furusawa** [comment]
そのイメージです

**Comment by AtsukiTak** [comment]
closeしまっす
