### ISSUE TITLE
[Story] Eagnaが、決まった時間に報酬処理できるようにする

### ISSUE THREAD

**Issue by Yuya-Furusawa** [eagna-io/Eagna#39]
Eagnaが、決まった時間に報酬処理をできるようにする。
===

### 誰にとって価値のあるストーリーですか？

- ユーザー 
- Eagna (aka 俺ら)

### 現状、どのような問題がありますか？

- Eagnaが報酬処理を忘れがち
- ユーザーが報酬の抽選が行われたのかわからない

### その問題をどのように解決しますか？

- 毎週決まった時間（e.g. 月曜日の0時）に１週間分まとめて報酬処理（抽選・配布）を行う

### その解決策によりどのような不利益が発生しますか？

- 決められた時間に、他の人間的活動を中断して処理を行わなくてはならない
    - コロコロ時間を変えるとユーザーを混乱させてしまう

### その問題を解決する手段として、どのような代替手段が思いつきますか？また、なぜその手段を選択しないのですか？

- ユーザーに報酬処理を行なった旨の通知を送る
    - 報酬処理忘れちゃうかも
    - リマインダーを使う

### どのような作業が想定されますか？

- [ ] 処理を行う時間を決める
- [ ] 処理を行う時間を決めたことをユーザーに通知する

**Comment by AtsukiTak** [comment]
いつにする？

**Comment by Yuya-Furusawa** [comment]
週のはじめとかがいいのかな
月曜日の0時とか？
あとその時間から処理を始めるのか、その前に処理しておいてその時間に告知するのか

**Comment by AtsukiTak** [comment]
月曜の０〜１時の間に処理をして、完了したら通知、て感じかな
