### ISSUE TITLE
[Story] マーケット作成者が、トークンの順番を指定しその順番で表示できるようにする

### ISSUE THREAD

**Issue by Yuya-Furusawa** [eagna-io/Eagna#40]
マーケット作成者が、トークンの順番を指定しその順番で表示できるようにする。
===

### 誰にとって価値のあるストーリーですか？

- ユーザー
- マーケット作成者

### 現状、どのような問題がありますか？

- トークンがランダムの順番で表示されているため、例えばスポーツの試合結果予想マーケットで「引き分け」トークンが一番最初にきてしまっている
- 「引き分け」トークンが一番最初にくるのは違和感

### その問題をどのように解決しますか？

- マーケット作成時にトークンの表示する順番を指定できるようにする

### その解決策によりどのような不利益が発生しますか？

- 特になし

### その問題を解決する手段として、どのような代替手段が思いつきますか？また、なぜその手段を選択しないのですか？

- 特になし

### どのような作業が想定されますか？

- [x] indexフィールドをmarket_tokensテーブルに追加する。デフォルトは0。
- [x] Market作成のロジックを修正。クライアントから投げられた順に index を埋めていく。
- [x] Market取得のロジックを修正。tokenをindex順にqueryする。

**Comment by AtsukiTak** [comment]
どうやってTokenモデルのindexを指定するか。

- indexフィールドをリクエストに含める
- リクエストの配列のindexを使用する

後方互換性、単純性からリクエストの配列のindexを使用する。

**Comment by AtsukiTak** [comment]
DBのmarket_tokensテーブルに、indexカラムを追加するか

- indexカラムを追加しない。unused_idカラムはinsert順になっているので、それでorder byする。
  - DBを変更しないで済む。
- indexカラムを追加する
  - 順番を気にしていることが明示的
  - DBに挿入後でも順番を変更できる

「indexカラムを追加する」ことにする。

**Comment by AtsukiTak** [comment]
Tokenモデルにindex属性を追加するか

- index属性を使用する機会はあるか
  - 今のとこない
- DBから取得するときにソートし、その後はそれを崩さなければよい
- **ソートしている旨をドキュメント化する**
